CREATE TABLE IF NOT EXISTS `ncaa_lacrosse`.`ncaa_schedules` (
  `year` int(11) DEFAULT NULL,
  `year_id` int(11) DEFAULT NULL,
  `team_id` int(11) DEFAULT NULL,
  `team_name` varchar(255) DEFAULT NULL,
  `game_date` varchar(255) DEFAULT '',
  `game_string` text,
  `opponent_id` int(11) DEFAULT NULL,
  `opponent_name` varchar(255) DEFAULT NULL,
  `opponent_url` text,
  `neutral_site` varchar(255) DEFAULT NULL,
  `neutral_location` text,
  `home_game` varchar(255) DEFAULT NULL,
  `score_string` text,
  `team_won` varchar(255) DEFAULT NULL,
  `score` text,
  `exempt` varchar(255) DEFAULT NULL,
  `team_score` decimal(11,0) DEFAULT NULL,
  `opponent_score` decimal(11,0) DEFAULT NULL,
  `overtime` varchar(255) DEFAULT NULL,
  `overtime_periods` varchar(11) DEFAULT NULL,
  `game_id` int(11) DEFAULT NULL,
  `game_url` text,
  UNIQUE KEY `unique_combo` (`team_id`,`game_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
